<ul id="nav" class="nav">
	<li<?php if ($this->active == 'home') {
		echo ' class="active"';
	}?>><a href="/admin/">Home</a></li>
	<li<?php if ($this->active == 'locations') {
		echo ' class="active"';
	}?>><a href="/admin/locations/">Locations</a></li>
	<li<?php if ($this->active == 'urls') {
		echo ' class="active"';
	}?>><a href="/admin/urls/">URLs</a></li>
	<li<?php if ($this->active == 'promotions') {
		echo ' class="active"';
	}?>><a href="/admin/promotions/">Promos</a></li>
	<li<?php if ($this->active == 'grabber') {
		echo ' class="active"';
	}?>><a href="/admin/grabber/">Grabber</a></li>
	<li><a href="http://178.63.18.3/phpmyadmin/">Phpmyadmin</a></li>
</ul>
<div class="clearfix"></div>
